version: '3'

services:
#  mysql_db:  # Couldn't set up this properly – wouldn't connect
#    image: mysql:latest
#    environment:
#      MYSQL_DATABASE: inventory_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_HOST: ''
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql:/var/lib/mysql/data

  postgres_db:
    image: postgres:12.10
    restart: unless-stopped
    env_file:
      - docker_compose.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  django:
    build:
      context: .
    command: bash ./runserver.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

volumes:
  mysql:
  postgres:
